#!/usr/bin/env sh
set -e

JSON_ENV=$(jq -n \
  --arg VITE_API_BASE_URL "$VITE_API_BASE_URL" \
  --arg VITE_API_MOCKING_ENABLED "$VITE_API_MOCKING_ENABLED" \
  --arg VITE_KEYCLOAK_URL "$VITE_KEYCLOAK_URL" \
  --arg VITE_KEYCLOAK_REALM "$VITE_KEYCLOAK_REALM" \
  --arg VITE_KEYCLOAK_CLIENT_ID "$VITE_KEYCLOAK_CLIENT_ID" \
  --arg VITE_BITCR_DEV_INCLUDE_CROWDIN_IN_CONTEXT_TOOLING "$VITE_BITCR_DEV_INCLUDE_CROWDIN_IN_CONTEXT_TOOLING" \
  '{VITE_API_BASE_URL: $VITE_API_BASE_URL, VITE_API_MOCKING_ENABLED: $VITE_API_MOCKING_ENABLED, VITE_KEYCLOAK_URL: $VITE_KEYCLOAK_URL, VITE_KEYCLOAK_REALM: $VITE_KEYCLOAK_REALM, VITE_KEYCLOAK_CLIENT_ID: $VITE_KEYCLOAK_CLIENT_ID, VITE_BITCR_DEV_INCLUDE_CROWDIN_IN_CONTEXT_TOOLING: $VITE_BITCR_DEV_INCLUDE_CROWDIN_IN_CONTEXT_TOOLING}')

cat <<EOF > /usr/share/nginx/html/config.js
window.__ENV__ = ${JSON_ENV};
EOF
